### ISSUE TITLE
No textures in Firefox with privacy.resistFingerprinting or webgl.min_capability_mode

### ISSUE THREAD

**Issue by kevinoid** [felixpalmer/peaks-of-austria#1]
This is a fascinating and beautiful project.  Thanks for creating it!

Just wanted to let you know that the textures do not appear in [Tor Browser](https://www.torproject.org/), or in Firefox when either [`privacy.resistFingerprinting`](https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting) or [`webgl.min_capability_mode`](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API#webgl_debugging_and_testing) is enabled in [`about:config`](https://support.mozilla.org/kb/about-config-editor-firefox).  This occurs because the maximum texture size is limited to 2048x2048 (or 1024x1024 for `webgl.min_capability_mode`), resulting in the following console warnings:

    THREE.WebGLRenderer: Image in DataTexture is too big (4096x4096).
    WebGL warning: texImage: Requested size at this level is unsupported.

I understand if fixing this is not a priority, since these conditions are currently rather niche.  Just opening the issue so you are aware.

Cheers, and thanks again for this project,
Kevin

P.S. See [Bugzilla Bug 1684230](https://bugzilla.mozilla.org/show_bug.cgi?id=1684230) for discussion on the Mozilla side.

**Comment by felixpalmer** [comment]
OK, interesting to know. Unfortunately cutting down the texture size isn't really possible while keeping the library working as designed, so this is a limitation that we will have to live with
